# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class ByteArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsByteArray(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ByteArray()
        x.Init(buf, n + offset)
        return x

    # ByteArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ByteArray
    def Bytes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ByteArray
    def BytesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ByteArray
    def BytesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ByteArray
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ByteArrayStart(builder): builder.StartObject(2)
def ByteArrayAddBytes(builder, bytes): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bytes), 0)
def ByteArrayStartBytesVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def ByteArrayAddType(builder, type): builder.PrependUint8Slot(1, type, 0)
def ByteArrayEnd(builder): return builder.EndObject()
