# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class Configurable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsConfigurable(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Configurable()
        x.Init(buf, n + offset)
        return x

    # Configurable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Configurable
    def ConfigurableName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # Configurable
    def ObservationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Configurable
    def Observation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ConfigurableStart(builder): builder.StartObject(3)
def ConfigurableAddConfigurableName(builder, configurableName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(configurableName), 0)
def ConfigurableAddObservationType(builder, observationType): builder.PrependUint8Slot(1, observationType, 0)
def ConfigurableAddObservation(builder, observation): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(observation), 0)
def ConfigurableEnd(builder): return builder.EndObject()
