# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

import flatbuffers

class Configuration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsConfiguration(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Configuration()
        x.Init(buf, n + offset)
        return x

    # Configuration
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Configuration
    def ConfigurableName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # Configuration
    def ConfigurableValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ConfigurationStart(builder): builder.StartObject(2)
def ConfigurationAddConfigurableName(builder, configurableName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(configurableName), 0)
def ConfigurationAddConfigurableValue(builder, configurableValue): builder.PrependFloat64Slot(1, configurableValue, 0.0)
def ConfigurationEnd(builder): return builder.EndObject()
