# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class ET(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsET(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ET()
        x.Init(buf, n + offset)
        return x

    # ET
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ET
    def Transform(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .EulerTransform import EulerTransform
            obj = EulerTransform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ETStart(builder): builder.StartObject(1)
def ETAddTransform(builder, transform): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(transform), 0)
def ETEnd(builder): return builder.EndObject()
