# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

class FBSObserverData(object):
    NONE = 0
    FBSByteArray = 1
    FBSNumeral = 2
    FBSString = 3
    FBSPosition = 4
    FBSRotation = 5
    FBSEulerTransform = 6
    FBSQuaternionTransformObservation = 7
    FBSBodyObservation = 8

