# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class Motor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMotor(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Motor()
        x.Init(buf, n + offset)
        return x

    # Motor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Motor
    def MotorName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # Motor
    def ValidInput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .Range import Range
            obj = Range()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Motor
    def EnergySpentSinceReset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def MotorStart(builder): builder.StartObject(3)
def MotorAddMotorName(builder, motorName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(motorName), 0)
def MotorAddValidInput(builder, validInput): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(validInput), 0)
def MotorAddEnergySpentSinceReset(builder, energySpentSinceReset): builder.PrependFloat32Slot(2, energySpentSinceReset, 0.0)
def MotorEnd(builder): return builder.EndObject()
