# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class OBS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOBS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OBS()
        x.Init(buf, n + offset)
        return x

    # OBS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OBS
    def ObservationName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # OBS
    def ObservationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OBS
    def Observation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def OBSStart(builder): builder.StartObject(3)
def OBSAddObservationName(builder, observationName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(observationName), 0)
def OBSAddObservationType(builder, observationType): builder.PrependUint8Slot(1, observationType, 0)
def OBSAddObservation(builder, observation): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(observation), 0)
def OBSEnd(builder): return builder.EndObject()
