# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

class Observation(object):
    NONE = 0
    Single = 1
    Triple = 2
    Array = 3
    RB = 4
    ET = 5
    QT = 6
    String = 7
    ByteArray = 8

