# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class QT(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsQT(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QT()
        x.Init(buf, n + offset)
        return x

    # QT
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QT
    def Transform(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .QuaternionTransform import QuaternionTransform
            obj = QuaternionTransform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def QTStart(builder): builder.StartObject(1)
def QTAddTransform(builder, transform): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(transform), 0)
def QTEnd(builder): return builder.EndObject()
