# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class RB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRB(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RB()
        x.Init(buf, n + offset)
        return x

    # RB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RB
    def Body(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .Body import Body
            obj = Body()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RBStart(builder): builder.StartObject(1)
def RBAddBody(builder, body): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(body), 0)
def RBEnd(builder): return builder.EndObject()
