# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

import flatbuffers

class ReactionParameters(object):
    __slots__ = ['_tab']

    # ReactionParameters
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReactionParameters
    def Terminable(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ReactionParameters
    def Step(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # ReactionParameters
    def Reset(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # ReactionParameters
    def Configure(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(3))
    # ReactionParameters
    def Describe(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # ReactionParameters
    def EpisodeCount(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(5))

def CreateReactionParameters(builder, terminable, step, reset, configure, describe, episodeCount):
    builder.Prep(1, 6)
    builder.PrependBool(episodeCount)
    builder.PrependBool(describe)
    builder.PrependBool(configure)
    builder.PrependBool(reset)
    builder.PrependBool(step)
    builder.PrependBool(terminable)
    return builder.Offset()
