# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class Single(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSingle(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Single()
        x.Init(buf, n + offset)
        return x

    # Single
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Single
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Single
    def Range(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .Range import Range
            obj = Range()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SingleStart(builder): builder.StartObject(2)
def SingleAddValue(builder, value): builder.PrependFloat64Slot(0, value, 0.0)
def SingleAddRange(builder, range): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(range), 0)
def SingleEnd(builder): return builder.EndObject()
