// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Neodroid.Messaging.Models.State
{

using global::System;
using global::FlatBuffers;

public struct FBSState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBSState GetRootAsFBSState(ByteBuffer _bb) { return GetRootAsFBSState(_bb, new FBSState()); }
  public static FBSState GetRootAsFBSState(ByteBuffer _bb, FBSState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool FBSStateBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "STAT"); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string EnvironmentName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetEnvironmentNameBytes() { return __p.__vector_as_arraysegment(4); }
  public float TotalEnergySpent { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public FBSActor? Actors(int j) { int o = __p.__offset(8); return o != 0 ? (FBSActor?)(new FBSActor()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ActorsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public FBSObserver? Observers(int j) { int o = __p.__offset(10); return o != 0 ? (FBSObserver?)(new FBSObserver()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ObserversLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int FrameNumber { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float Reward { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool Interrupted { get { int o = __p.__offset(16); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public FBSEnvironmentDescription? EnvironmentDescription { get { int o = __p.__offset(18); return o != 0 ? (FBSEnvironmentDescription?)(new FBSEnvironmentDescription()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string DebugMessage { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetDebugMessageBytes() { return __p.__vector_as_arraysegment(20); }

  public static Offset<FBSState> CreateFBSState(FlatBufferBuilder builder,
      StringOffset environment_nameOffset = default(StringOffset),
      float total_energy_spent = 0.0f,
      VectorOffset actorsOffset = default(VectorOffset),
      VectorOffset observersOffset = default(VectorOffset),
      int frame_number = 0,
      float reward = 0.0f,
      bool interrupted = false,
      Offset<FBSEnvironmentDescription> environment_descriptionOffset = default(Offset<FBSEnvironmentDescription>),
      StringOffset debug_messageOffset = default(StringOffset)) {
    builder.StartObject(9);
    FBSState.AddDebugMessage(builder, debug_messageOffset);
    FBSState.AddEnvironmentDescription(builder, environment_descriptionOffset);
    FBSState.AddReward(builder, reward);
    FBSState.AddFrameNumber(builder, frame_number);
    FBSState.AddObservers(builder, observersOffset);
    FBSState.AddActors(builder, actorsOffset);
    FBSState.AddTotalEnergySpent(builder, total_energy_spent);
    FBSState.AddEnvironmentName(builder, environment_nameOffset);
    FBSState.AddInterrupted(builder, interrupted);
    return FBSState.EndFBSState(builder);
  }

  public static void StartFBSState(FlatBufferBuilder builder) { builder.StartObject(9); }
  public static void AddEnvironmentName(FlatBufferBuilder builder, StringOffset environmentNameOffset) { builder.AddOffset(0, environmentNameOffset.Value, 0); }
  public static void AddTotalEnergySpent(FlatBufferBuilder builder, float totalEnergySpent) { builder.AddFloat(1, totalEnergySpent, 0.0f); }
  public static void AddActors(FlatBufferBuilder builder, VectorOffset actorsOffset) { builder.AddOffset(2, actorsOffset.Value, 0); }
  public static VectorOffset CreateActorsVector(FlatBufferBuilder builder, Offset<FBSActor>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartActorsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddObservers(FlatBufferBuilder builder, VectorOffset observersOffset) { builder.AddOffset(3, observersOffset.Value, 0); }
  public static VectorOffset CreateObserversVector(FlatBufferBuilder builder, Offset<FBSObserver>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartObserversVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddFrameNumber(FlatBufferBuilder builder, int frameNumber) { builder.AddInt(4, frameNumber, 0); }
  public static void AddReward(FlatBufferBuilder builder, float reward) { builder.AddFloat(5, reward, 0.0f); }
  public static void AddInterrupted(FlatBufferBuilder builder, bool interrupted) { builder.AddBool(6, interrupted, false); }
  public static void AddEnvironmentDescription(FlatBufferBuilder builder, Offset<FBSEnvironmentDescription> environmentDescriptionOffset) { builder.AddOffset(7, environmentDescriptionOffset.Value, 0); }
  public static void AddDebugMessage(FlatBufferBuilder builder, StringOffset debugMessageOffset) { builder.AddOffset(8, debugMessageOffset.Value, 0); }
  public static Offset<FBSState> EndFBSState(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBSState>(o);
  }
  public static void FinishFBSStateBuffer(FlatBufferBuilder builder, Offset<FBSState> offset) { builder.Finish(offset.Value, "STAT"); }
};

public struct FBSActor : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBSActor GetRootAsFBSActor(ByteBuffer _bb) { return GetRootAsFBSActor(_bb, new FBSActor()); }
  public static FBSActor GetRootAsFBSActor(ByteBuffer _bb, FBSActor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSActor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ActorName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetActorNameBytes() { return __p.__vector_as_arraysegment(4); }
  public FBSMotor? Motors(int j) { int o = __p.__offset(6); return o != 0 ? (FBSMotor?)(new FBSMotor()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MotorsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FBSActor> CreateFBSActor(FlatBufferBuilder builder,
      StringOffset actor_nameOffset = default(StringOffset),
      VectorOffset motorsOffset = default(VectorOffset)) {
    builder.StartObject(2);
    FBSActor.AddMotors(builder, motorsOffset);
    FBSActor.AddActorName(builder, actor_nameOffset);
    return FBSActor.EndFBSActor(builder);
  }

  public static void StartFBSActor(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddActorName(FlatBufferBuilder builder, StringOffset actorNameOffset) { builder.AddOffset(0, actorNameOffset.Value, 0); }
  public static void AddMotors(FlatBufferBuilder builder, VectorOffset motorsOffset) { builder.AddOffset(1, motorsOffset.Value, 0); }
  public static VectorOffset CreateMotorsVector(FlatBufferBuilder builder, Offset<FBSMotor>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartMotorsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FBSActor> EndFBSActor(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBSActor>(o);
  }
};

public struct FBSObserver : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBSObserver GetRootAsFBSObserver(ByteBuffer _bb) { return GetRootAsFBSObserver(_bb, new FBSObserver()); }
  public static FBSObserver GetRootAsFBSObserver(ByteBuffer _bb, FBSObserver obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSObserver __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ObserverName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetObserverNameBytes() { return __p.__vector_as_arraysegment(4); }
  public string DataType { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetDataTypeBytes() { return __p.__vector_as_arraysegment(6); }
  public byte Data(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(8); }
  public FBSTransform? Transform { get { int o = __p.__offset(10); return o != 0 ? (FBSTransform?)(new FBSTransform()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public FBSBody? Body { get { int o = __p.__offset(12); return o != 0 ? (FBSBody?)(new FBSBody()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartFBSObserver(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddObserverName(FlatBufferBuilder builder, StringOffset observerNameOffset) { builder.AddOffset(0, observerNameOffset.Value, 0); }
  public static void AddDataType(FlatBufferBuilder builder, StringOffset dataTypeOffset) { builder.AddOffset(1, dataTypeOffset.Value, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(2, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddTransform(FlatBufferBuilder builder, Offset<FBSTransform> transformOffset) { builder.AddStruct(3, transformOffset.Value, 0); }
  public static void AddBody(FlatBufferBuilder builder, Offset<FBSBody> bodyOffset) { builder.AddStruct(4, bodyOffset.Value, 0); }
  public static Offset<FBSObserver> EndFBSObserver(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBSObserver>(o);
  }
};

public struct FBSEnvironmentDescription : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBSEnvironmentDescription GetRootAsFBSEnvironmentDescription(ByteBuffer _bb) { return GetRootAsFBSEnvironmentDescription(_bb, new FBSEnvironmentDescription()); }
  public static FBSEnvironmentDescription GetRootAsFBSEnvironmentDescription(ByteBuffer _bb, FBSEnvironmentDescription obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSEnvironmentDescription __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int MaxEpisodeLength { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float SolvedThreshold { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public FBSConfigurable? Configurables(int j) { int o = __p.__offset(8); return o != 0 ? (FBSConfigurable?)(new FBSConfigurable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ConfigurablesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FBSEnvironmentDescription> CreateFBSEnvironmentDescription(FlatBufferBuilder builder,
      int max_episode_length = 0,
      float solved_threshold = 0.0f,
      VectorOffset configurablesOffset = default(VectorOffset)) {
    builder.StartObject(3);
    FBSEnvironmentDescription.AddConfigurables(builder, configurablesOffset);
    FBSEnvironmentDescription.AddSolvedThreshold(builder, solved_threshold);
    FBSEnvironmentDescription.AddMaxEpisodeLength(builder, max_episode_length);
    return FBSEnvironmentDescription.EndFBSEnvironmentDescription(builder);
  }

  public static void StartFBSEnvironmentDescription(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddMaxEpisodeLength(FlatBufferBuilder builder, int maxEpisodeLength) { builder.AddInt(0, maxEpisodeLength, 0); }
  public static void AddSolvedThreshold(FlatBufferBuilder builder, float solvedThreshold) { builder.AddFloat(1, solvedThreshold, 0.0f); }
  public static void AddConfigurables(FlatBufferBuilder builder, VectorOffset configurablesOffset) { builder.AddOffset(2, configurablesOffset.Value, 0); }
  public static VectorOffset CreateConfigurablesVector(FlatBufferBuilder builder, Offset<FBSConfigurable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartConfigurablesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FBSEnvironmentDescription> EndFBSEnvironmentDescription(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBSEnvironmentDescription>(o);
  }
};

public struct FBSConfigurable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBSConfigurable GetRootAsFBSConfigurable(ByteBuffer _bb) { return GetRootAsFBSConfigurable(_bb, new FBSConfigurable()); }
  public static FBSConfigurable GetRootAsFBSConfigurable(ByteBuffer _bb, FBSConfigurable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSConfigurable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ConfigurableName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetConfigurableNameBytes() { return __p.__vector_as_arraysegment(4); }
  public FBSInputRange? ValidInput { get { int o = __p.__offset(6); return o != 0 ? (FBSInputRange?)(new FBSInputRange()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartFBSConfigurable(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddConfigurableName(FlatBufferBuilder builder, StringOffset configurableNameOffset) { builder.AddOffset(0, configurableNameOffset.Value, 0); }
  public static void AddValidInput(FlatBufferBuilder builder, Offset<FBSInputRange> validInputOffset) { builder.AddStruct(1, validInputOffset.Value, 0); }
  public static Offset<FBSConfigurable> EndFBSConfigurable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBSConfigurable>(o);
  }
};

public struct FBSMotor : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBSMotor GetRootAsFBSMotor(ByteBuffer _bb) { return GetRootAsFBSMotor(_bb, new FBSMotor()); }
  public static FBSMotor GetRootAsFBSMotor(ByteBuffer _bb, FBSMotor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSMotor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string MotorName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetMotorNameBytes() { return __p.__vector_as_arraysegment(4); }
  public FBSInputRange? ValidInput { get { int o = __p.__offset(6); return o != 0 ? (FBSInputRange?)(new FBSInputRange()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float EnergyCost { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EnergySpentSinceReset { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartFBSMotor(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddMotorName(FlatBufferBuilder builder, StringOffset motorNameOffset) { builder.AddOffset(0, motorNameOffset.Value, 0); }
  public static void AddValidInput(FlatBufferBuilder builder, Offset<FBSInputRange> validInputOffset) { builder.AddStruct(1, validInputOffset.Value, 0); }
  public static void AddEnergyCost(FlatBufferBuilder builder, float energyCost) { builder.AddFloat(2, energyCost, 0.0f); }
  public static void AddEnergySpentSinceReset(FlatBufferBuilder builder, float energySpentSinceReset) { builder.AddFloat(3, energySpentSinceReset, 0.0f); }
  public static Offset<FBSMotor> EndFBSMotor(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBSMotor>(o);
  }
};

public struct FBSVec3 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSVec3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<FBSVec3> CreateFBSVec3(FlatBufferBuilder builder, float X, float Y, float Z) {
    builder.Prep(4, 12);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<FBSVec3>(builder.Offset);
  }
};

public struct FBSQuat : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSQuat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public float W { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<FBSQuat> CreateFBSQuat(FlatBufferBuilder builder, float X, float Y, float Z, float W) {
    builder.Prep(4, 16);
    builder.PutFloat(W);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<FBSQuat>(builder.Offset);
  }
};

public struct FBSTransform : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSTransform __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FBSVec3 Position { get { return (new FBSVec3()).__assign(__p.bb_pos + 0, __p.bb); } }
  public FBSVec3 Rotation { get { return (new FBSVec3()).__assign(__p.bb_pos + 12, __p.bb); } }
  public FBSVec3 Direction { get { return (new FBSVec3()).__assign(__p.bb_pos + 24, __p.bb); } }

  public static Offset<FBSTransform> CreateFBSTransform(FlatBufferBuilder builder, float position_X, float position_Y, float position_Z, float rotation_X, float rotation_Y, float rotation_Z, float direction_X, float direction_Y, float direction_Z) {
    builder.Prep(4, 36);
    builder.Prep(4, 12);
    builder.PutFloat(direction_Z);
    builder.PutFloat(direction_Y);
    builder.PutFloat(direction_X);
    builder.Prep(4, 12);
    builder.PutFloat(rotation_Z);
    builder.PutFloat(rotation_Y);
    builder.PutFloat(rotation_X);
    builder.Prep(4, 12);
    builder.PutFloat(position_Z);
    builder.PutFloat(position_Y);
    builder.PutFloat(position_X);
    return new Offset<FBSTransform>(builder.Offset);
  }
};

public struct FBSBody : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSBody __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FBSVec3 Velocity { get { return (new FBSVec3()).__assign(__p.bb_pos + 0, __p.bb); } }
  public FBSVec3 AngularVelocity { get { return (new FBSVec3()).__assign(__p.bb_pos + 12, __p.bb); } }

  public static Offset<FBSBody> CreateFBSBody(FlatBufferBuilder builder, float velocity_X, float velocity_Y, float velocity_Z, float angular_velocity_X, float angular_velocity_Y, float angular_velocity_Z) {
    builder.Prep(4, 24);
    builder.Prep(4, 12);
    builder.PutFloat(angular_velocity_Z);
    builder.PutFloat(angular_velocity_Y);
    builder.PutFloat(angular_velocity_X);
    builder.Prep(4, 12);
    builder.PutFloat(velocity_Z);
    builder.PutFloat(velocity_Y);
    builder.PutFloat(velocity_X);
    return new Offset<FBSBody>(builder.Offset);
  }
};

public struct FBSInputRange : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBSInputRange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int DecimalGranularity { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public float MaxInputValue { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float MinInputValue { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<FBSInputRange> CreateFBSInputRange(FlatBufferBuilder builder, int DecimalGranularity, float MaxInputValue, float MinInputValue) {
    builder.Prep(4, 12);
    builder.PutFloat(MinInputValue);
    builder.PutFloat(MaxInputValue);
    builder.PutInt(DecimalGranularity);
    return new Offset<FBSInputRange>(builder.Offset);
  }
};


}
